### ISSUE TITLE
error when extending from recommended

### ISSUE THREAD

**Issue by mallorybulkley** [jest-community/eslint-plugin-jest#102] opened 2018-03-22 19:30 UTC
After adding `plugin:jest/recommended` to my eslintrc "extends", get this error in prefer-to-have-length:

```ESLint stack trace:
[Error - 15:27:19] TypeError: context.getSourceCode(...).getFirstTokenBetween is not a function
    at EventEmitter.CallExpression (.../node_modules/eslint-plugin-jest/rules/prefer-to-have-length.js:33:14)```

**Comment by ranyitz** [comment] 2018-03-22 19:43
Hey @mallorybulkley, can you provide a repro?

**Comment by trevordmiller** [comment] 2018-03-26 18:15
@ranyitz I'm getting this as well with latest `eslint-plugin-jest` (`^21.14.1`) and an `.eslintrc` with:

```
  "extends": ["airbnb", "plugin:jest/recommended"]
```

**Comment by ranyitz** [comment] 2018-03-26 18:27
@trevordmiller can you give a path to the recreation of the issue, or a github repo that I can install and reproduces this bug?

**Comment by trevordmiller** [comment] 2018-03-26 18:28
@ranyitz `eslint --init` and add `"extends": ["airbnb", "plugin:jest/recommended"]` :)

**Comment by trevordmiller** [comment] 2018-03-26 19:34
Could be related to `airbnb`? @mallorybulkley could you provide your reproducing repo?

**Comment by mallorybulkley** [comment] 2018-03-27 00:14
I think either my version of eslint wasn't compatible or possibly something was wrong with having different versions installed globally vs in my project. I was able to fix by uninstalling my global eslint and eslint-plugin-jest and upgrading the versions in my project repo to the latest.

**Comment by G-Rath** [comment] 2020-01-20 04:46
I'm going to close this, since it seems like it was resolved. Feel free to open a fresh new issue if you've still got problems :)

**Closed by G-Rath** 2020-01-20 04:46 UTC
Labels: question
