### ISSUE TITLE
version 24.1.2 - breaking change - Prefer using 'test' instead of 'it' within describe

### ISSUE THREAD

**Issue by genrym** [jest-community/eslint-plugin-jest#712] opened 2020-11-12 12:33 UTC
Hi. 
After upgrading to version `24.1.2` (from `24.1.0`) - we started to get the following:

`Prefer using 'test' instead of 'it' within describe (jest/consistent-test-it)`

Was it an expected change in this version?

**Comment by SimenB** [comment] 2020-11-12 13:17
Duplicate of #711

**Closed by SimenB** 2020-11-12 13:17 UTC
