### ISSUE TITLE
Error while loading rule

### ISSUE THREAD

**Issue by dacevedo12** [jest-community/eslint-plugin-jest#1268] opened 2022-10-18 14:44 UTC
After updating to eslint-plugin-jest: 27.1.2

```
TypeError: Error while loading rule 'jest/no-deprecated-functions': (0 , _utils2.detectJestVersion) is not a function
    at create (/path/to/node_modules/eslint-plugin-jest/lib/rules/no-deprecated-functions.js:41:303)
```

Perhaps it may be confusing the import as both a utils.js and utils/index.js exist in the same `lib/rules` directory

**Comment by G-Rath** [comment] 2022-10-18 18:38
@dacevedo12 can you please provide more details about your setup? i.e. version of node and other packages being used, eslint config, how you're invoking eslint, etc - ideally a sample repo reproducing the issue would be great.

**Comment by G-Rath** [comment] 2022-11-24 19:54
I'm going to close this since I can't reproduce it and typically these errors are the result of local/project level issues.

**Closed by G-Rath** 2022-11-24 19:54 UTC
