### ISSUE TITLE
[no-standalone-expect]: false positive for expect.extend: no-standalone-expect

### ISSUE THREAD

**Issue by tomi** [jest-community/eslint-plugin-jest#1190] opened 2022-08-08 07:57 UTC
I'm extending expect with a custom rule using `expect.extend`, that is in the module root level. This results to an error:

> error  Expect must be inside of a test block  jest/no-standalone-expect

I don't believe this should be an error. I think there might be some regression since this came up in a renovate PR to update `eslint-plugin-jest` from 26.7.0 -> 26.8.0

**Comment by G-Rath** [comment] 2022-08-08 08:03
Duplicate of #1186

**Closed by G-Rath** 2022-08-08 08:03 UTC
