### ISSUE TITLE
[no-identical-title] not working correctly with nested describe blocks

### ISSUE THREAD

**Issue by Haberkamp** [jest-community/eslint-plugin-jest#1176] opened 2022-07-29 09:29 UTC
In our test suite nest describe blocks a lot. And sometimes we try to test the same behaviour with different behaviours of the user. And we use reuse the title of the tests. The linter marks two lines as error because it were reusing the same title but in different describe blocks. Generally this shouldn't be an issue because the titles would be the following:

`src/components/table/DataGrid/DataGrid > when the user checks the header checkbox > should select all rows`

and 

`src/components/table/DataGrid/DataGrid > when the user checks all rows > should select all rows `

Here, a screenshot of the whole test suite.

<img width="578" alt="Bildschirmfoto 2022-07-29 um 11 24 40" src="https://user-images.githubusercontent.com/35109813/181728878-f2f69633-c88b-4b3c-b535-0f0415207100.png">

**Comment by G-Rath** [comment] 2022-07-29 09:35
Hmmm yeah that actually looks like a regression, except somehow our test suit is still passing 🤔

Is it just with todos by chance?

**Comment by G-Rath** [comment] 2022-07-29 20:23
@Haberkamp I'm not able to reproduce this - could you check that you're using the latest version of `eslint-plugin-jest`? Ideally it would be best if you could put together a reproduction repo that I could clone :)

**Comment by G-Rath** [comment] 2022-08-26 23:08
Closing per my previous comment

**Closed by G-Rath** 2022-08-26 23:08 UTC
Labels: bug, rule: no-identical-title
