### ISSUE TITLE
[expect-expect]: For usability, narrow warning range to the test definition, not the body.

### ISSUE THREAD

**Issue by jeffvandyke** [jest-community/eslint-plugin-jest#641] opened 2020-08-10 15:23 UTC
Often when working (in either Vim using ALE or in VSCode using ESLint), I'll be writing a test, this rule violation will cover the whole test body until I've written in the `expect()` line, which hides other warnings that I'm more interested in while I'm writing the test, because I'm still setting up things to `expect`, which usually takes some time to write. Sometimes, I put an `expect(false)` just so that I can see lints about arrays, promises, and other such things while I'm typing, and needing to put in a dummy `expect` while I'm writing the tests seems unnecessary and flow-interrupting.

I think this would be best solved by keeping this rule, but only highlighting as a warning the name of the test instead of the entire body, to make room for other lints to show up. Thoughts or other ideas?

**Comment by G-Rath** [comment] 2020-08-10 19:48
Duplicate of #539.

The tl;dr is that this is an IDE problem - the node we're reporting on is the right one as it's the closest to the actual error which is that the function is missing an `expect` assertion. We can't account for how IDEs render these errors, and a change to improve the experience in one might worsen it in another.

**Comment by jeffvandyke** [comment] 2020-08-10 20:49
@G-Rath, I disagree with this analysis: I think there's an important semantic in the `range` returned from lint rules, and this rule is hurting more than helping in what it reports as the problem range.

I think more than one IDE (VSCode and Vim) is interpreting a violation's range in a reasonable way - by marking that code from beginning to end as a problem visually, but violations of this rule are normal when writing tests, so it's normal to have this rule say that there's a problem with the test from beginning to end, hiding all other more important errors (I place this error in the same usefulness category as no-unused-vars - good check, but likely going to be fixed soon). I think in the tradeoff between what's convenient for this rule's logic and what's convenient for the user, the balance shifts heavily toward reporting a smaller range due to how very inconvenient it is for the user and how often we run into this - every time we write a test.

For an analogy, imagine a teacher marking up a student's first draft, highlighting grammar and spelling errors. Imagine the student missed one of the requirements that this paper needed to use a source from Encyclopedia Britannica. Should the teacher a): write a note on the top indicating the missed requirement, or b): highlight the entire paper from beginning to end, saying that he/she couldn't find the required citation anywhere in the paper? I think that the same answer applies here as well.

This rule's range reporting has apparently been the subject of complaint quite a few times before this, in <https://github.com/jest-community/eslint-plugin-jest/issues/539>, <https://github.com/microsoft/vscode-eslint/issues/370>, and <https://github.com/jest-community/eslint-plugin-jest/pull/599>, so it seems obvious that it's a hinderance for lots of people.

For all these reasons, I implore the authors here to reconsider taking a look at this pull request: <https://github.com/jest-community/eslint-plugin-jest/pull/599>, and keep the usefulness of this rule while significantly improving the developer's experience.

**Closed** 2023-10-20 21:59 UTC
Labels: rule: expect-expect
