### ISSUE TITLE
Reference unexpected had more than one definition

### ISSUE THREAD

**Issue by diegovilar** [jest-community/eslint-plugin-jest#1114] opened 2022-05-17 01:14 UTC
If you define both a value and a type using the same identifier (perfectly valid TypeScript code), I get a `Reference unexpected had more than one definition` error :

![image](https://user-images.githubusercontent.com/759416/168707199-86a13333-0331-455b-833e-e3532ce726be.png)

The image in question points to `jest/consistent-test-it`, but if I disable it, another rule throws the same error.

If I rename either the type or the value identifier it, works.

**Comment by G-Rath** [comment] 2022-05-17 01:15
Duplicate of #1108 - please upgrade to the latest version :)

**Closed by G-Rath** 2022-05-17 01:15 UTC
