### ISSUE TITLE
no-done-callback false positive with jest-cucumber

### ISSUE THREAD

**Issue by potb** [jest-community/eslint-plugin-jest#1095] opened 2022-04-28 09:05 UTC
This code leads to a false-positive since a callback is passed to a function named ``test``.
The warning disappears when the ``test`` function is renamed to something else.

jest: 27.5.1
eslint-plugin-jest: 26.1.4

```ts
import { defineFeature, loadFeature } from "jest-cucumber";

const feature = loadFeature("some/feature");

defineFeature(feature, (test) => {
  test("A scenario", ({ given, when, then }) => {});
});
```

**Comment by G-Rath** [comment] 2022-04-28 09:20
This is a duplicate of #556 - I've got a draft PR up that should be landed "soon", but I'm the meantime you can either call the method something else or not run eslint-plugin-jest on these files per our readme.

**Closed** 2022-04-28 09:20 UTC

**Comment by potb** [comment] 2022-04-28 09:28
Alright, thanks.

**Comment by G-Rath** [comment] 2022-05-14 21:29
@potb this is now resolved :)

**Comment by potb** [comment] 2022-05-14 22:56
> @potb this is now resolved :)

Thanks for letting me know
