### ISSUE TITLE
jest@25.7.0: Throwing `Environment key "jest/globals" is unknown`

### ISSUE THREAD

**Issue by Brianzchen** [jest-community/eslint-plugin-jest#1031] opened 2022-01-17 21:02 UTC
I haven't changed anything but lowering down the 25.6.0 works

**Comment by G-Rath** [comment] 2022-01-17 21:07
Duplicate of #44 - please ensure all your eslint dependencies are updated.

**Closed by G-Rath** 2022-01-17 21:07 UTC
