### ISSUE TITLE
new rule request: valid-each

### ISSUE THREAD

**Issue by benmonro** [jest-community/eslint-plugin-jest#493] opened 2019-12-02 22:31 UTC
when using a `describe.each` or `test.each` it would be nice to have a rule to ensure that the pretty formatting or `$variable` injection is used to ensure the results are unique.

for example, rule would report on 
`test.each([1,2,3])("Should square the number", () => {...})`
 
but not report on 

`test.each([1,2,3])("Should square %i", () => {...})`

**Comment by G-Rath** [comment] 2020-12-24 23:08
Closing as a duplicate of #359

**Closed** 2020-12-26 18:32 UTC
Labels: duplicate, new rule
