### ISSUE TITLE
Feature request: add rule that prevents jest methods being used in files that do not end with .spec.js / spec.js

### ISSUE THREAD

**Issue by CodingSpiderFox** [jest-community/eslint-plugin-jest#1372] opened 2023-05-13 13:37 UTC
Sometimes it can happen that you don't recognize a mistyped file name.
Most jest configs would not pick up these files and some test might not be run then.

**Comment by G-Rath** [comment] 2023-05-13 19:29
Duplicate of #68

**Closed by G-Rath** 2023-05-13 19:29 UTC
