### ISSUE TITLE
Missing dependency on typescript

### ISSUE THREAD

**Issue by aqeelat** [jest-community/eslint-plugin-jest#1687] opened 2024-12-18 12:58 UTC
After installing eslint-plugin-jest, yarn is reporting:
`p99bfd → ✘ eslint-plugin-jest@npm:28.9.0 [d12f2] doesn't provide typescript to @typescript-eslint/utils@npm:8.18.1 [ebbdd] and 2 other dependencies`

**Comment by G-Rath** [comment] 2024-12-18 18:15
Duplicate of #1117 - https://github.com/typescript-eslint/typescript-eslint/issues/10383 is likely going to address this

**Closed by G-Rath** 2024-12-18 18:15 UTC
