### ISSUE TITLE
New rule: Do not allow promises in expect without an await

### ISSUE THREAD

**Issue by prashantjainlacework** [jest-community/eslint-plugin-jest#1053] opened 2022-02-08 01:49 UTC
Most of the assertions happen after a few awaits or waitFors. Developers often assert a generic function which returns a promise e.g.
`expect(getAsyncElement(...)).toBeInTheDocument().`

The above code has resulted in hours of debugging why the assertion failed.

The right way to write this is ...
`expect(await getAsyncElement(...)).toBeInTheDocument().`

It would be nice to enforce the await in the expect.

**Comment by G-Rath** [comment] 2022-02-08 01:51
Duplicate of #804

**Closed by G-Rath** 2022-02-08 01:51 UTC
