### ISSUE TITLE
ESLint v9 support

### ISSUE THREAD

**Issue by pierluigilenoci** [jest-community/eslint-plugin-jest#1669] opened 2024-11-06 16:29 UTC
ESLint 8 has been EOL since October 5, 2024.
Is there any ETA for migration?
https://eslint.org/blog/2024/09/eslint-v8-eol-version-support/#eslint-v8.x-end-of-life-is-october-5%2C-2024

Ref: https://github.com/eslint/eslint/issues/18391

**Comment by JoshuaKGoldberg** [comment] 2024-11-06 16:51
Duplicate of #1546, no?

**Comment by G-Rath** [comment] 2024-11-06 16:56
As @JoshuaKGoldberg said, this is a duplicate - we already support v9

**Closed** 2024-11-06 16:55 UTC
