### ISSUE TITLE
Use in `overrides` applies the rules to all files, not just to the matched ones

### ISSUE THREAD

**Issue by hon2a** [jest-community/eslint-plugin-jest#491] opened 2019-12-02 13:13 UTC
### Setup

`.eslintrc`
```json
{
  "extends": [
    "eslint:recommended",
    "prettier"
  ],
  "parserOptions": { … },
  "parser": "babel-eslint",
  "env": { … },
  "rules": { … },
  "overrides": [
    {
      "files": ["src/**/*.test.js", "!src/api/**/*.*"],
      "extends": "plugin:jest/recommended"
    },
    …
  ]
}
```

### Expected

It should apply the "recommended" ruleset from `eslint-plugin-jest` only on the files matching `src/**/*.test.js` (with the exception of `!src/api/**/*.*`).

### Actual

It applies the Jest ruleset to all my source files, namely to the Cypress test files `cypress/**/*.js`, which are most certainly not matched by the `files` selector. (This produces hundreds of errors in my codebase, as the test environments are quite different.)

### Notes

Support for using `extends` inside `overrides` has been added in ESLint 6 and works with other rules and plugins I'm using. But this issue can be reproduced without it, e.g. with:

```json
{
  …,
  "overrides": [
    {
      "files": ["src/**/*.test.js", "!src/api/**/*.*"],
      "plugins": ["jest"],
      "rules": {
        "jest/expect-expect": "error"
      }
    }
  ]
}
```

which again applies the `jest/expect-expect` rule to files clearly not matched by the `files` selector.

**Comment by G-Rath** [comment] 2019-12-02 17:38
My understanding is that `overrides` is a completely eslint-core feature - plugins don't have to do anything to support it.

We've also had eslint setups working using overrides by other users of this plugin, as it was the solution recommended for some issues. I also just tested it myself to be sure, and it works fine.

I suspect the issue is with your setup. I won't close the issue outright, but would you be able to provide a code sandbox with a slice of your setup for comparison?

**Comment by G-Rath** [comment] 2019-12-02 17:41
Actually, I've confirmed the issue is what I suspected: You shouldn't use negation in `files` ,as the globs are applied separately.

Instead, you should use the `excluded Files` field.
What's happening is that you're saying:

> "every file that is in the path of src, that ends with .test.js OR *any file* that is not in src/api"

Instead, you want this:
```
files: ["src/**/*.test.js"],
excludedFiles: ["src/api/**.*"]
```

**Closed by G-Rath** 2019-12-02 17:41 UTC

**Comment by hon2a** [comment] 2019-12-02 19:36
@G-Rath Thanks a lot for that investigation! Now I wonder if it ever worked differently (as I seem to remember solving a similar conflict with it) or if it's just my misconception from the start. In any case, now I know better; sorry for taking up your time to figure it out.
