### ISSUE TITLE
prefer-inline-snapshots max length

### ISSUE THREAD

**Issue by chrisblossom** [jest-community/eslint-plugin-jest#297] opened 2019-07-09 18:36 UTC
I'd like to see an option for `prefer-inline-snapshots` that would only recommend inline snapshots that are under X lines long.

**Comment by jeysal** [comment] 2019-07-10 08:47
Sounds like a good idea, although given the difficulties encountered in https://github.com/jest-community/eslint-plugin-jest/pull/282, unless those are solved it would mean the rule would need to be changed to report errors in the snap file :|

**Comment by alexkrolick** [comment] 2019-07-31 18:23
Dupe of #244

**Comment by jeysal** [comment] 2019-07-31 20:15
true

**Closed by jeysal** 2019-07-31 20:15 UTC
Labels: duplicate
